# Generated by Django 5.2.7 on 2025-10-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('instructions', models.CharField(max_length=300)),
                ('target_muscles', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50, null=True)),
                ('difficulty', models.CharField(max_length=30)),
                ('tips', models.CharField(max_length=300)),
            ],
        ),
    ]
