# Generated by Django 5.2.7 on 2025-10-02 06:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workoutplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('mon', 'monday'), ('tue', 'tuesday'), ('wed', 'wednesday'), ('thur', 'thursday'), ('fri', 'friday'), ('sat', 'saturday'), ('sun', 'sunday')], max_length=9)),
                ('reps', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('sets', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('priority', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
