# Generated by Django 5.2.7 on 2025-10-02 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_workoutplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workoutplan',
            constraint=models.UniqueConstraint(fields=('user', 'weekday', 'priority'), name='Unique_Constraint_for_workout'),
        ),
        migrations.AddConstraint(
            model_name='workoutplan',
            constraint=models.UniqueConstraint(fields=('user', 'weekday'), name='Unique_Constraint_for_user_weekday'),
        ),
    ]
