# Generated by Django 5.2.7 on 2025-10-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_workoutplan_unique_constraint_for_workout_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workoutplan',
            name='Unique_Constraint_for_user_weekday',
        ),
    ]
