# Generated by Django 5.2.7 on 2025-10-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0004_remove_workoutplan_unique_constraint_for_user_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='weekday',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], max_length=9),
        ),
    ]
