# Generated by Django 5.2.7 on 2025-10-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0005_alter_workoutplan_weekday'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workoutplan',
            name='Unique_Constraint_for_workout',
        ),
    ]
