# Generated by Django 5.2.7 on 2025-10-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0007_completedworkouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
