# Generated by Django 5.2.7 on 2025-10-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0008_workoutplan_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedworkouts',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.workoutplan'),
        ),
    ]
