# Generated by Django 5.2.7 on 2025-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0010_goalweight_weightentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
